# Generated by Django 5.2.12 on 2026-03-31 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDeteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('patron', models.TextField()),
                ('tipo', models.CharField(choices=[('escaneo', 'Escaneo'), ('fuerza_bruta', 'Fuerza bruta'), ('exceso', 'Exceso'), ('custom', 'Custom')], max_length=20)),
                ('umbral_peticiones', models.IntegerField(default=10)),
                ('ventana_minutos', models.IntegerField(default=5)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Regla de detección',
                'verbose_name_plural': 'Reglas de detección',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(max_length=45, validators=[django.core.validators.validate_ipv46_address])),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('sistema_operativo', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('pais', models.CharField(blank=True, max_length=60)),
                ('codigo_pais', models.CharField(blank=True, max_length=2)),
                ('motivo', models.CharField(choices=[('escaneo', 'Escaneo de vulnerabilidades'), ('exceso', 'Exceso de peticiones'), ('fuerza_bruta', 'Fuerza bruta')], max_length=30)),
                ('peticiones', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_bloqueo', models.DateTimeField(db_index=True)),
                ('activo', models.BooleanField(default=True)),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.regladeteccion')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='monitor.servidor')),
            ],
            options={
                'ordering': ['-fecha_bloqueo'],
            },
        ),
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('total_bloqueos', models.IntegerField(default=0)),
                ('total_peticiones', models.IntegerField(default=0)),
                ('pais_top', models.CharField(blank=True, max_length=60)),
                ('ip_top', models.CharField(blank=True, max_length=45)),
                ('por_tipo', models.JSONField(default=dict)),
                ('por_pais', models.JSONField(default=dict)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='monitor.servidor')),
            ],
            options={
                'verbose_name': 'Métrica diaria',
                'verbose_name_plural': 'Métricas diarias',
                'unique_together': {('servidor', 'fecha')},
            },
        ),
    ]
