# Generated by Django 5.2.12 on 2026-03-31 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#C8A951', max_length=7)),
                ('default_w', models.IntegerField(default=16)),
                ('default_h', models.IntegerField(default=12)),
                ('categoria', models.CharField(blank=True, default='general', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modificado'],
            },
        ),
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('grid_x', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('grid_w', models.IntegerField(default=16)),
                ('grid_h', models.IntegerField(default=12)),
                ('z_index', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='monitor.cardmodule')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='monitor.dashboard')),
            ],
            options={
                'ordering': ['z_index', 'creado'],
            },
        ),
    ]
