# Generated by Django 5.2.12 on 2026-03-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_cardmodule_dashboard_cardinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueo',
            name='rutas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
