# Generated by Django 5.2.12 on 2026-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_bloqueo_rutas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('primera_visita', models.DateTimeField(auto_now_add=True)),
                ('ultima_visita', models.DateTimeField(auto_now=True)),
                ('peticiones', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-ultima_visita'],
            },
        ),
    ]
