# Generated by Django 5.2.12 on 2026-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_visita_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='regladeteccion',
            name='metodo',
            field=models.CharField(blank=True, choices=[('', 'Cualquiera'), ('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='', max_length=10),
        ),
    ]
